### ISSUE TITLE
xPfxImpot: fail to import multiple certificates in the same configuration

### ISSUE THREAD

**Issue by baldator** [PowerShell/CertificateDsc#126] opened 2018-03-27 14:23 UTC
**Details of the scenario you tried and the problem that is occurring:**
If I try to import multiple certificate in the same configuration or if I run the same configuration twice quickly I get the following error:

PowerShell DSC resource MSFT_xPfxImport  failed to execute Set-TargetResource functionality with error message: Cannot validate argument on parameter 'Thumbprint'. Exception calling "GetTypes" with "0" argument(s): "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."

I tried to narrow down the problem and it looks like the problem is in the begin block of the Test-Thumbprint function (CertificateDSc.Common.psm1).

**The DSC configuration that is using the resource (as detailed as possible):**
I'm trying to automating the installation and configuration of an ADFS/WAP farm. The part of the configuration causing problem is looping on the list of sites and for each site it does the following:

````powershell
xPfxImport $certificateName
{
	Ensure 	   = 'Present'
	Thumbprint = $site.CertificateThumbprint
	Path       = "C:\temp\$certificateName"
	Location   = 'LocalMachine'
	Store      = 'MY'
	Credential = $CertificatePassword
	DependsOn  = "[xRemoteFile]$certificateName"
}
````
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 - PS 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
I tried on 3.2.0.0 and 3.1.0.0

**Comment by PlagueHO** [comment] 2018-03-29 22:48
Hi @baldator - just so I can understand the issue, you're doing something like this in your config (or running the above config twice quickly):
```powershell
xPfxImport $certificateName1
{
	Ensure 	   = 'Present'
	Thumbprint = $CertificateThumbprint1
	Path       = "C:\temp\$certificateName"
	Location   = 'LocalMachine'
	Store      = 'MY'
	Credential = $CertificatePassword1
	DependsOn  = "[xRemoteFile]$certificateName1"
}
xPfxImport $certificateName2
{
	Ensure 	   = 'Present'
	Thumbprint = $CertificateThumbprint2
	Path       = "C:\temp\$certificateName2"
	Location   = 'LocalMachine'
	Store      = 'MY'
	Credential = $CertificatePassword2
	DependsOn  = "[xRemoteFile]$certificateName2"
}
```
There is only one place that this error looks like it could occur and that is retrieving the hash providers for validating this thumbprint.

I also did some additional testing on Test-Thumbprint and it did show up another issue (completely not related), but I couldn't get the error you're seeing (I'll report this issue in a separate issue/PR).

If you Import the module `CertificateDSc.Common.psm1` and then run the command `Test-Thumbprint -Thumbprint $site.CertificateThumbprint` (you'll need $site.CertificateThumbprint to be set to whatever you'd normally set it in your config), can you run this command repeatedly without error?

**Comment by baldator** [comment] 2018-03-30 08:26
Hi @PlagueHO,
Thank you for your answer. I'm actually looping on xPfxImport, so I'm executing a configuration similar to the one you posted.

I tried to import the module CertificateDSc.Common.psm1 and to run Test-Thumbprint twice (on the same server experiencing the issue): the function runs as expected with no errors. However if I run it in the DSC context it fails the second exection. 

Please tell me if I can help you better understand or troubleshoot the problem.

Thanks,
Marco

**Comment by tlavoieNGPVAN** [comment] 2018-07-31 12:53
I also ran into this bug, I was able to work around the issue by changing the validation on thumbprints
from:
[ValidateScript( { $_ | Test-Thumbprint } )]
to:
[ValidateNotNullOrEmpty()]

This allowed multiple certificates to install without issue.

**Comment by sgreenlee11** [comment] 2018-10-11 15:21
I also see the same issue using Windows Server 2016 and the Azure Pull Service. What I've found is that if I have a configuration with just the xPfxImport resource the issue does no repro. It's only when this resource is added to a configuration with many other resources that it starts to pop up. I've tried narrowing down to specific resources, but so far have not been able to.

**Comment by shurick81** [comment] 2018-12-10 17:48
Getting the following error in 4.1 and 4.2 versions:

```
PowerShell DSC resource MSFT_PfxImport  failed to execute Test-TargetResource functionality with error message: Cannot
validate argument on parameter 'Thumbprint'. Exception calling "GetTypes" with "0" argument(s): "Unable to load one or
more of the requested types. Retrieve the LoaderExceptions property for more information."
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : OOS01
```

It works fine when I only have this resource:

```
            PfxImport $hostName
            {
                Thumbprint  = $pfx.thumbprint
                Path        = $pfxPath
                Location    = 'LocalMachine'
                Store       = 'My'
                Credential  = $pfxCredential
            }
```

But if I add this to configuration:
```
            OfficeOnlineServerFarm Farm
            {
                InternalURL                 = "https://oos.unionen.local"
                EditingEnabled              = $true
                CertificateName             = "oos.unionen.local"
            }
```

It throws the aforementioned exception.
I use Windows 2016 Server on this machine.

**Comment by sgreenlee11** [comment] 2019-01-24 15:45
As mentioned, it looks like the issue is with this line in Test-Thumbprint:

`        $allHashProviders = [System.AppDomain]::CurrentDomain.GetAssemblies().GetTypes()
`
A similar bug was opened with the cAzureStorage module: https://github.com/azureautomation/modules/issues/3

It seems like the underlying issue is the same, related to missing dependant types. After doing some testing it seems that the assemblies required to retrieve the cryptography providers are all present in the Global Assembly Cache. I was able to resolve this issue in my testing by replacing the line above with the following lines:

`        $gacassembly  = [System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object -FilterScript {$_.GlobalAssemblyCache -eq $true}
        $allHashProviders = $gacassembly.GetTypes()
`

On Windows Server 2016 I verified that the same hash providers were found using this method over pulling all assemblies.

**Comment by ykuijs** [comment] 2019-03-20 13:13
Is this issue fixed via PR #186?

**Comment by PlagueHO** [comment] 2019-03-20 16:10
I think so @ykuijs - although I was never able to repro it. I could repro the issue @sgreenlee11 documented.

**Comment by ykuijs** [comment] 2019-03-20 20:56
I was able to repro the issue: I encountered this issue today on one of the servers in my SharePoint farm in Azure. After updating the resource to the new code, the issue was resolved. So it indeed looks like it is solved.,

**Comment by PlagueHO** [comment] 2019-03-21 02:08
Awesome - thanks for checking this @ykuijs . I'll close this issue for now and we can reopen it after the next release goes out if it still occurs.

**Closed by PlagueHO** 2019-03-21 02:08 UTC
Labels: bug, help wanted

**Comment by sgreenlee11** [comment] 2019-03-21 12:49
I confirmed that the issue I was able to reproduce was solved by the latest Dev branch as well.
